version: '3.1'

services:

  mongo: 
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root 
    #   MONGO_INITDB_ROOT_PASSWORD: ezer123
    ports:
      - 3001:27017
  
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    # volumes:
    #   - ~/Pocs/DOCKER_VOLUMES/REDIS_PLANETAS:/bitnami/redis/data